extends Node


# Declare member variables here. Examples:
# var a = 2
# var b = "text"

signal statusUpdate
signal fileDownloaded

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.

func _on_statusUpdate(update):
	emit_signal("statusUpdate", update)
	
func _on_file_downloaded(download):
	emit_signal("fileDownloaded", download)
# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
