extends Spatial


# Declare member variables here. Examples:
# var a = 2
# var b = "text"
var latMin:float = 0
var latMax:float = 1
var lonMin:float = 0.0
var lonMax:float = 1.0
var resolution:int = 512
var radius:float = 10
var scaleFact:int = 1

var origin:Vector3
var center:Vector3

func setParams(latMinIN, latMaxIN, lonMinIN, lonMaxIN, resolutionIN, radiusIN:float, scaleFactIN):
	latMin = latMinIN
	latMax = latMaxIN
	lonMin = lonMinIN
	lonMax = lonMaxIN
	resolution = resolutionIN
	radius = radiusIN
	scaleFact = scaleFactIN
	
# Called when the node enters the scene tree for the first time.
func _ready():
	.get_node("Mesh").setParams(latMin, latMax, lonMin, lonMax, resolution, radius, scaleFact)
	.get_node("Mesh").genMesh()
	.get_node("Origin").transform.origin = .get_node("Mesh").origin
	.get_node("Center").transform.origin = .get_node("Mesh").center
	#.translate(.get_node("Mesh").origin)

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
